#!/bin/bash
# Paths to the differents applications on the server machines
tomcat_path="/home/emmanuelh/Softwares/apache-tomcat-9.0.0.M26"
directory_path="/home/emmanuelh/Documents/serverPython"
mapshaper_path="/home/emmanuelh/Git/mapshaper"
#Database informations
host="localhost"
user="postgres"
password="postgres"
database="StructureJudiciaire"

# Commands to stop or start the apache tomcat server according to the paths
stop_tomcat="sh $tomcat_path/bin/shutdown.sh"
launch_tomcat="sh $tomcat_path/bin/startup.sh"

# final files
LieuxJustice="annuaire_lieux_justice"
TGI="annuaire_tgi"
TI="annuaire_ti"
Greffes="liste_des_greffes"
Personnes="personne"

# Infinite loop to allow the user to enter differents commands
while true
do
  read -p "start - stop `echo $'\n> '`" answer

  # (2) handle the input we were given
  case $answer in
    "start" ) eval $launch_tomcat
    # Set the envoronment path variable
    PATH=$PATH:$HOME/FWTools/bin_safe
    # Export the database infos into shapefiles
    for file in $LieuxJustice $TGI $TI $Greffes $Personnes
    do
      pgsql2shp -f "$directory_path/$file" -h $host -u $user -P $password $database "SELECT * FROM $file"
    done
    # Export shapefiles into geojson
    eval "$mapshaper_path/bin/mapshaper $directory_path/*.shp -o $directory_path/ format=geojson"
    # Remove temporary files
    rm *.shp *.shx *.prj *.dbf *.cpg
    # Move the geojson files to the server
    for file in $LieuxJustice $TGI $TI $Greffes $Personnes
    do
      eval "cp $file.json $tomcat_path/webapps/geojson/"
    done
  ;;

    "stop" ) eval $stop_tomcat
    exit;;

    * )     echo "Bad command";;
  esac
done
