#!/bin/bash

if [ $# -eq 0 ]
then
  echo "$0 : Pas d'arguments passés"
  exit 1
fi
if [ $# -eq 2 ]
then
  bin/mapshaper $1*.shp -o $2 format=geojson
  exit 0
fi

if [ $1 == "-help" ]
then
  echo "./json2shp [Original_shapefiles_directory] [Destination_json_directory]"
fi
