#!/bin/bash

if [ $# -eq 0 ]
then
  echo "$0 : Pas d'arguments passés"
  exit 1
fi
if [ $# -eq 2 ]
then
  ogr2ogr -f GeoJSON -t_srs EPSG:4326 -s_srs EPSG:4326 $1 $2
  exit 0
fi

if [ $1 == "-help" ]
then
  echo "./json2shp [DESTINATION.json] [FILE_TO_EXPORT.shp]"
fi
